name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install libraries
      run: sudo apt install libgl-dev libglew-dev libsdl2-dev libsdl2-image-dev
    - name: create dirs
      run: mkdir bin
    - name: make
      run: make -j
