name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install librarys
      run: sudo apt install libgl-dev libglew-dev libsdl2-dev libsdl2-image-dev
    - name: make
      run: make -j
